/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ringcentral.kotlin.demo
import com.ringcentral.RestClient
import com.ringcentral.definitions.TokenInfo
import io.github.cdimascio.dotenv.dotenv

val dotenv = dotenv()

class App {
    fun testAuthorize(): TokenInfo {
        val rc = RestClient(
                dotenv["RINGCENTRAL_CLIENT_ID"],
                dotenv["RINGCENTRAL_CLIENT_SECRET"],
                dotenv["RINGCENTRAL_SERVER_URL"]
        )
        println("done1")
        return rc.authorize(
                dotenv["RINGCENTRAL_USERNAME"],
                dotenv["RINGCENTRAL_EXTENSION"],
                dotenv["RINGCENTRAL_PASSWORD"]
        )
    }
}

fun main() {
    App().testAuthorize()
    println("done")
}
