/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ringcentral.kotlin.demo

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasATestAuthorize() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.testAuthorize(), "app should have a greeting")
    }
}
